import type { Metadata } from 'next';
import Link from 'next/link';
import {
  Users, Target, CheckSquare, CreditCard, Zap, BarChart3,
  ArrowRight, Play, Shield, Globe2, Sparkles, ChevronDown,
  Building2, GraduationCap, TrendingUp, Clock, Star,
} from 'lucide-react';
import { CRMPricingSection } from '@/components/crm-product/CRMPricingSection';

export const metadata: Metadata = {
  title: 'EdTech CRM — Admissions Management Software | HelpingBots',
  description:
    'HelpingBots EdTech CRM is built for Indian admissions teams — manage leads, track pipeline, collect fees, and measure team performance. 7 role types, WhatsApp integration, mobile-first. Try free for 14 days.',
  keywords: [
    'EdTech CRM', 'admissions management software', 'lead management for education',
    'student enrollment CRM', 'coaching institute CRM', 'education CRM India',
    'admissions pipeline software', 'fee collection software', 'EdTech software India',
    'HelpingBots CRM', 'RBAC CRM', 'multi-role CRM',
  ],
  alternates: { canonical: 'https://helpingbots.in/products/crm' },
  openGraph: {
    title: 'HelpingBots EdTech CRM — Built for Admissions Teams',
    description: 'The only CRM designed specifically for EdTech admissions — 7 RBAC roles, full pipeline, fee collection, and team leaderboards. Try free.',
    url: 'https://helpingbots.in/products/crm',
    type: 'website',
    images: [{ url: '/og-image.png', width: 1200, height: 630, alt: 'HelpingBots EdTech CRM' }],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'HelpingBots EdTech CRM — Built for Admissions',
    description: '7 roles, 10-stage pipeline, WhatsApp integration, fee tracking. Built for Indian EdTech. Try free 14 days.',
    images: ['/og-image.png'],
  },
};

// ─── Structured data ──────────────────────────────────────────────────────────

const jsonLd = {
  '@context': 'https://schema.org',
  '@type': 'SoftwareApplication',
  name: 'HelpingBots EdTech CRM',
  applicationCategory: 'BusinessApplication',
  operatingSystem: 'Web, iOS, Android',
  url: 'https://helpingbots.in/products/crm',
  description:
    'A production-grade CRM built specifically for EdTech admissions teams — role-based access, lead pipeline management, student onboarding, and payment tracking.',
  offers: [
    { '@type': 'Offer', price: '4999', priceCurrency: 'INR', name: 'Starter Plan' },
    { '@type': 'Offer', price: '12999', priceCurrency: 'INR', name: 'Professional Plan' },
  ],
  publisher: { '@type': 'Organization', name: 'HelpingBots', url: 'https://helpingbots.in' },
  aggregateRating: { '@type': 'AggregateRating', ratingValue: '4.9', reviewCount: '38' },
};

// ─── Static data ──────────────────────────────────────────────────────────────

const FEATURES = [
  {
    icon: Shield,
    title: 'Role-Based Access Control',
    desc: '7 roles — Super Admin, Admin, Team Lead, Marketing, Sales, Support, and Student. Every person sees only what they need to see.',
    color: 'text-primary bg-primary/10',
  },
  {
    icon: Target,
    title: 'Smart Lead Pipeline',
    desc: '10-stage admissions pipeline from New Lead to Enrolled. Visual progress, status tracking, and automated next follow-up dates.',
    color: 'text-amber-600 bg-amber-100 dark:bg-amber-900/30',
  },
  {
    icon: CheckSquare,
    title: 'Task & Follow-up Engine',
    desc: 'Assign Call, Email, WhatsApp, Meeting, or Document tasks. Attach a specific student to each task so your team never loses context.',
    color: 'text-blue-600 bg-blue-100 dark:bg-blue-900/30',
  },
  {
    icon: CreditCard,
    title: 'Fee Collection & Tracking',
    desc: 'Record full and instalment payments, generate invoice numbers, track pending amounts, and send reminders — all in one screen.',
    color: 'text-emerald-600 bg-emerald-100 dark:bg-emerald-900/30',
  },
  {
    icon: Zap,
    title: 'Marketing Attribution',
    desc: '"Generated By" tracking shows exactly which marketing executive created each lead, so you can measure quality, not just quantity.',
    color: 'text-orange-600 bg-orange-100 dark:bg-orange-900/30',
  },
  {
    icon: BarChart3,
    title: 'Team Leaderboards',
    desc: 'Separate leaderboards for Marketing (lead generation) and Sales (conversions). Best and worst performer spotlights, period-based filtering.',
    color: 'text-violet-600 bg-violet-100 dark:bg-violet-900/30',
  },
] as const;

const STEPS = [
  {
    num: '01',
    title: 'Import or add leads instantly',
    desc: 'Upload a CSV from your ad campaigns or add leads manually. Fields auto-map, duplicates get flagged, and every lead lands in your pipeline within seconds.',
    icon: Users,
  },
  {
    num: '02',
    title: 'Assign, track, and follow up',
    desc: 'The Team Lead assigns leads to Sales Executives. Tasks appear in their daily queue. Pipeline status updates in real time as students move through stages.',
    icon: Target,
  },
  {
    num: '03',
    title: 'Close deals and collect fees',
    desc: 'Once a student is confirmed, Support Agents take over for fee collection, document gathering, and onboarding. Everything tracked, nothing missed.',
    icon: TrendingUp,
  },
] as const;

const FOR_WHO = [
  { icon: GraduationCap, label: 'Coaching Institutes', desc: 'JEE, NEET, UPSC, MBA prep' },
  { icon: Building2,     label: 'EdTech Startups',    desc: 'Online courses & bootcamps' },
  { icon: Globe2,        label: 'Study Abroad',        desc: 'University placement agencies' },
  { icon: Star,          label: 'K-12 Schools',        desc: 'Admissions & counselling teams' },
] as const;

const FAQS = [
  {
    q: 'Can I try before I pay?',
    a: 'Yes — every plan includes a 14-day free trial, no credit card required. You can also try the live interactive demo on this page right now.',
  },
  {
    q: 'Is my data safe and private?',
    a: 'All data is encrypted in transit (TLS 1.3) and at rest (AES-256). We are SOC 2 Type II compliant. Your student data is never shared with third parties.',
  },
  {
    q: 'Does it work on mobile?',
    a: "Yes — HelpingBots CRM is mobile-first. Your counsellors can add leads, complete tasks, and call students directly from their phone browser. No app install needed.",
  },
  {
    q: 'Can I integrate WhatsApp?',
    a: 'WhatsApp integration is included in the Professional and Enterprise plans. Tasks can be created as "WhatsApp" type, and bulk messaging via the WhatsApp Business API is available on Enterprise.',
  },
  {
    q: 'How many leads can I import?',
    a: 'Starter supports 500 leads/month. Professional is unlimited. Enterprise adds custom batch sizes, priority validation, and auto-deduplication across branches.',
  },
  {
    q: 'Do you offer white-labelling?',
    a: 'White-label branding (your logo, domain, and colour palette) is available on the Enterprise plan. Contact us for a demo of the branded version.',
  },
] as const;

// ─── Page ─────────────────────────────────────────────────────────────────────

export default function CRMProductPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      <div className="min-h-screen overflow-hidden">

        {/* ══════════════════════════════════════════════════════════════════
            HERO
        ══════════════════════════════════════════════════════════════════ */}
        <section className="relative pb-20 pt-32">
          {/* Background */}
          <div
            className="pointer-events-none absolute inset-0 -z-10 opacity-40"
            style={{ background: 'var(--gradient-mesh)' }}
          />
          <div className="pointer-events-none absolute left-1/3 top-20 -z-10 h-96 w-96 rounded-full bg-primary/15 blur-3xl" />
          <div className="pointer-events-none absolute right-1/4 top-40 -z-10 h-72 w-72 rounded-full bg-accent/15 blur-3xl" />

          <div className="container mx-auto px-4">
            <div className="mx-auto max-w-4xl text-center">

              {/* Eyebrow */}
              <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/5 px-4 py-1.5">
                <Sparkles className="h-3.5 w-3.5 text-primary" aria-hidden="true" />
                <span className="text-sm font-semibold text-primary">
                  Built for Indian EdTech admissions teams
                </span>
              </div>

              {/* Headline */}
              <h1 className="mb-6 text-4xl font-extrabold leading-[1.15] tracking-tight md:text-6xl lg:text-7xl">
                The CRM That{' '}
                <span className="text-gradient">Closes More</span>
                <br />Admissions
              </h1>

              {/* Subheading */}
              <p className="mx-auto mb-10 max-w-2xl text-lg text-muted-foreground md:text-xl">
                From the first Google Ad click to fee-paid enrollment — HelpingBots CRM gives your
                entire admissions team a single system of record, built specifically for how
                EdTech companies actually work.
              </p>

              {/* CTAs */}
              <div className="flex flex-col items-center justify-center gap-4 sm:flex-row">
                <Link
                  href="mailto:hello@helpingbots.in?subject=CRM Free Trial"
                  className="inline-flex items-center gap-2 rounded-xl bg-primary px-7 py-3.5 text-base font-bold text-primary-foreground shadow-lg transition-all hover:opacity-90 hover:-translate-y-0.5"
                >
                  Start Free 14-Day Trial
                  <ArrowRight className="h-4 w-4" aria-hidden="true" />
                </Link>
                <Link
                  href="/crm"
                  className="inline-flex items-center gap-2 rounded-xl border border-border bg-background px-7 py-3.5 text-base font-bold text-foreground transition-all hover:bg-muted hover:-translate-y-0.5"
                >
                  <Play className="h-4 w-4 text-primary" aria-hidden="true" />
                  Live Interactive Demo
                </Link>
              </div>

              {/* Social proof micro */}
              <p className="mt-6 text-sm text-muted-foreground">
                <span className="font-semibold text-foreground">38+ institutes</span> managing
                their admissions pipeline · ★★★★★ 4.9/5
              </p>
            </div>

            {/* ── Dashboard Preview (CSS-rendered, no image needed) ─────────── */}
            <div className="mx-auto mt-16 max-w-5xl">
              <div className="relative overflow-hidden rounded-2xl border border-border/50 bg-card shadow-2xl ring-1 ring-border/20">
                {/* Browser chrome */}
                <div className="flex items-center gap-2 border-b border-border bg-muted/50 px-4 py-3">
                  <div className="h-3 w-3 rounded-full bg-red-400" />
                  <div className="h-3 w-3 rounded-full bg-amber-400" />
                  <div className="h-3 w-3 rounded-full bg-emerald-400" />
                  <div className="ml-4 flex-1 rounded-md bg-background px-3 py-1 text-xs text-muted-foreground">
                    helpingbots.in/crm/dashboard
                  </div>
                </div>

                {/* Mock dashboard */}
                <div className="flex">
                  {/* Sidebar */}
                  <div className="hidden w-48 shrink-0 border-r border-border bg-muted/30 p-3 sm:block">
                    <div className="mb-4 flex items-center gap-2 px-2">
                      <div className="h-6 w-6 rounded-md bg-primary/20" />
                      <div className="h-3 w-24 rounded bg-muted-foreground/20" />
                    </div>
                    {['Dashboard', 'Leads', 'Tasks', 'Payments', 'Team'].map((item, i) => (
                      <div
                        key={item}
                        className={`mb-1 flex items-center gap-2 rounded-lg px-2 py-2 ${i === 0 ? 'bg-primary/10 text-primary' : ''}`}
                      >
                        <div className={`h-3.5 w-3.5 rounded ${i === 0 ? 'bg-primary/40' : 'bg-muted-foreground/20'}`} />
                        <span className={`text-xs ${i === 0 ? 'font-semibold text-primary' : 'text-muted-foreground'}`}>{item}</span>
                      </div>
                    ))}
                  </div>

                  {/* Main content */}
                  <div className="flex-1 p-4">
                    {/* KPI row */}
                    <div className="mb-4 grid grid-cols-2 gap-3 sm:grid-cols-4">
                      {[
                        { label: 'Active Leads', val: '19', color: 'text-foreground' },
                        { label: 'Enrolled', val: '4', color: 'text-emerald-600' },
                        { label: 'Revenue', val: '₹14.8L', color: 'text-primary' },
                        { label: 'Tasks Overdue', val: '2', color: 'text-red-500' },
                      ].map((card) => (
                        <div key={card.label} className="rounded-xl border border-border bg-card p-3">
                          <p className="text-[10px] text-muted-foreground">{card.label}</p>
                          <p className={`text-lg font-bold ${card.color}`}>{card.val}</p>
                        </div>
                      ))}
                    </div>
                    {/* Mini table */}
                    <div className="rounded-xl border border-border bg-card">
                      <div className="border-b border-border px-3 py-2">
                        <div className="h-3 w-24 rounded bg-muted-foreground/20" />
                      </div>
                      {['Ananya Sharma', 'Rohan Mehta', 'Priya Singh', 'Arjun Tiwari'].map((name) => (
                        <div key={name} className="flex items-center gap-3 border-b border-border/50 px-3 py-2 last:border-0">
                          <div className="h-7 w-7 shrink-0 rounded-full bg-primary/10" />
                          <div className="flex-1">
                            <div className="h-2.5 w-28 rounded bg-muted-foreground/30" />
                            <div className="mt-1 h-2 w-20 rounded bg-muted-foreground/15" />
                          </div>
                          <div className="h-5 w-16 rounded-full bg-emerald-100" />
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              </div>

              <p className="mt-3 text-center text-xs text-muted-foreground">
                ↑ Actual CRM interface — click "Live Interactive Demo" above to explore it yourself
              </p>
            </div>
          </div>
        </section>

        {/* ══════════════════════════════════════════════════════════════════
            STATS BAR
        ══════════════════════════════════════════════════════════════════ */}
        <section className="border-y border-border bg-muted/30 py-8">
          <div className="container mx-auto px-4">
            <div className="flex flex-wrap items-center justify-center gap-6 text-center md:gap-12">
              {[
                { val: '7', label: 'Role Types' },
                { val: '10', label: 'Pipeline Stages' },
                { val: '₹ UPI', label: 'Indian Payments' },
                { val: '100%', label: 'Mobile-First' },
                { val: '48h', label: 'Avg Onboarding' },
                { val: '14d', label: 'Free Trial' },
              ].map((stat) => (
                <div key={stat.label} className="min-w-[80px]">
                  <p className="text-2xl font-extrabold text-foreground md:text-3xl">{stat.val}</p>
                  <p className="text-xs font-medium text-muted-foreground">{stat.label}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ══════════════════════════════════════════════════════════════════
            FEATURES
        ══════════════════════════════════════════════════════════════════ */}
        <section className="py-24">
          <div className="container mx-auto px-4">
            <div className="mb-14 text-center">
              <h2 className="mb-4 text-3xl font-bold tracking-tight md:text-4xl">
                Everything your admissions team needs
              </h2>
              <p className="mx-auto max-w-xl text-muted-foreground">
                Purpose-built for the EdTech sales cycle — from cold lead to enrolled student.
              </p>
            </div>

            <div className="mx-auto grid max-w-6xl gap-5 md:grid-cols-2 lg:grid-cols-3">
              {FEATURES.map((feat) => {
                const Icon = feat.icon;
                return (
                  <div
                    key={feat.title}
                    className="group rounded-2xl border border-border bg-card p-6 transition-all duration-300 hover:border-primary/30 hover:shadow-md"
                  >
                    <div className={`mb-4 inline-flex h-11 w-11 items-center justify-center rounded-xl ${feat.color}`}>
                      <Icon className="h-5 w-5" aria-hidden="true" />
                    </div>
                    <h3 className="mb-2 font-bold text-foreground">{feat.title}</h3>
                    <p className="text-sm leading-relaxed text-muted-foreground">{feat.desc}</p>
                  </div>
                );
              })}
            </div>
          </div>
        </section>

        {/* ══════════════════════════════════════════════════════════════════
            HOW IT WORKS
        ══════════════════════════════════════════════════════════════════ */}
        <section className="bg-muted/30 py-24">
          <div className="container mx-auto px-4">
            <div className="mb-14 text-center">
              <h2 className="mb-4 text-3xl font-bold tracking-tight md:text-4xl">
                How it works in 3 steps
              </h2>
              <p className="text-muted-foreground">
                From first contact to fully enrolled — your entire admissions process, automated.
              </p>
            </div>

            <div className="mx-auto grid max-w-5xl gap-8 md:grid-cols-3">
              {STEPS.map((step, idx) => {
                const Icon = step.icon;
                return (
                  <div key={step.num} className="relative text-center">
                    {/* Connector line */}
                    {idx < STEPS.length - 1 && (
                      <div className="absolute left-[calc(50%+3rem)] right-0 top-8 hidden h-px bg-gradient-to-r from-border to-transparent md:block" />
                    )}
                    <div className="mx-auto mb-5 flex h-16 w-16 items-center justify-center rounded-2xl border-2 border-primary/30 bg-primary/10">
                      <Icon className="h-7 w-7 text-primary" aria-hidden="true" />
                    </div>
                    <p className="mb-1.5 text-sm font-bold uppercase tracking-widest text-primary">
                      Step {step.num}
                    </p>
                    <h3 className="mb-3 text-lg font-bold text-foreground">{step.title}</h3>
                    <p className="text-sm leading-relaxed text-muted-foreground">{step.desc}</p>
                  </div>
                );
              })}
            </div>
          </div>
        </section>

        {/* ══════════════════════════════════════════════════════════════════
            WHO IT'S FOR
        ══════════════════════════════════════════════════════════════════ */}
        <section className="py-20">
          <div className="container mx-auto px-4 text-center">
            <h2 className="mb-3 text-2xl font-bold text-foreground md:text-3xl">
              Built for every EdTech business model
            </h2>
            <p className="mb-10 text-muted-foreground">
              Whether you run 10 counsellors or 200, this CRM scales with you.
            </p>
            <div className="mx-auto flex flex-wrap justify-center gap-4 md:max-w-3xl">
              {FOR_WHO.map(({ icon: Icon, label, desc }) => (
                <div
                  key={label}
                  className="flex items-center gap-3 rounded-2xl border border-border bg-card px-5 py-4 shadow-sm"
                >
                  <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-primary/10">
                    <Icon className="h-5 w-5 text-primary" aria-hidden="true" />
                  </div>
                  <div className="text-left">
                    <p className="text-sm font-semibold text-foreground">{label}</p>
                    <p className="text-xs text-muted-foreground">{desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ══════════════════════════════════════════════════════════════════
            PRICING  (client component — has currency toggle)
        ══════════════════════════════════════════════════════════════════ */}
        <section className="border-t border-border bg-muted/20">
          <CRMPricingSection />
        </section>

        {/* ══════════════════════════════════════════════════════════════════
            DEMO CTA BANNER
        ══════════════════════════════════════════════════════════════════ */}
        <section className="py-20">
          <div className="container mx-auto px-4">
            <div className="relative overflow-hidden rounded-3xl border border-primary/20 bg-gradient-to-br from-primary/10 via-background to-accent/10 p-10 text-center shadow-elevated md:p-16">
              {/* Background orbs */}
              <div className="pointer-events-none absolute left-0 top-0 h-64 w-64 -translate-x-1/2 -translate-y-1/2 rounded-full bg-primary/10 blur-3xl" />
              <div className="pointer-events-none absolute bottom-0 right-0 h-64 w-64 translate-x-1/2 translate-y-1/2 rounded-full bg-accent/10 blur-3xl" />

              <div className="relative">
                <p className="mb-3 text-sm font-bold uppercase tracking-widest text-primary">
                  Try it yourself
                </p>
                <h2 className="mb-5 text-3xl font-extrabold tracking-tight text-foreground md:text-5xl">
                  See the CRM in action —{' '}
                  <span className="text-gradient">right now</span>
                </h2>
                <p className="mx-auto mb-8 max-w-xl text-muted-foreground md:text-lg">
                  No demo call required. Switch between 7 roles, add leads, assign tasks,
                  and collect payments — all in our live interactive demo.
                </p>
                <div className="flex flex-col items-center justify-center gap-4 sm:flex-row">
                  <Link
                    href="/crm"
                    className="inline-flex items-center gap-2 rounded-xl bg-primary px-8 py-4 text-base font-bold text-primary-foreground shadow-lg transition-all hover:opacity-90 hover:-translate-y-0.5"
                  >
                    <Play className="h-5 w-5" aria-hidden="true" />
                    Open Live Demo
                  </Link>
                  <Link
                    href="mailto:hello@helpingbots.in?subject=CRM Demo Request"
                    className="inline-flex items-center gap-2 rounded-xl border border-border bg-background px-8 py-4 text-base font-bold text-foreground transition-all hover:bg-muted"
                  >
                    <Clock className="h-5 w-5 text-primary" aria-hidden="true" />
                    Book a Guided Demo
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* ══════════════════════════════════════════════════════════════════
            FAQ
        ══════════════════════════════════════════════════════════════════ */}
        <section className="border-t border-border py-24">
          <div className="container mx-auto px-4">
            <div className="mx-auto max-w-3xl">
              <h2 className="mb-10 text-center text-3xl font-bold tracking-tight">
                Frequently Asked Questions
              </h2>

              <div className="space-y-3">
                {FAQS.map(({ q, a }) => (
                  <details
                    key={q}
                    className="group rounded-xl border border-border bg-card open:border-primary/30"
                  >
                    <summary className="flex cursor-pointer list-none items-center justify-between gap-4 px-5 py-4 font-semibold text-foreground">
                      <span>{q}</span>
                      <ChevronDown
                        className="h-4 w-4 shrink-0 text-muted-foreground transition-transform group-open:rotate-180"
                        aria-hidden="true"
                      />
                    </summary>
                    <div className="px-5 pb-4 pt-0 text-sm leading-relaxed text-muted-foreground">
                      {a}
                    </div>
                  </details>
                ))}
              </div>

              <p className="mt-8 text-center text-sm text-muted-foreground">
                Still have questions?{' '}
                <Link href="mailto:hello@helpingbots.in" className="font-medium text-primary hover:underline">
                  hello@helpingbots.in
                </Link>
                {' '}— we reply within 24 hours.
              </p>
            </div>
          </div>
        </section>

      </div>
    </>
  );
}