// ─────────────────────────────────────────────────────────────────────────────
// HelpingBots CRM — Static Demo Data
// All screens pull from this file. Data is internally consistent:
// lead IDs → tasks, payments, activities all cross-reference correctly.
// ─────────────────────────────────────────────────────────────────────────────

import type {
  AuditLog,
  DashboardMetric,
  ImportJob,
  ImportRow,
  Lead,
  LeadActivity,
  LeaderboardEntry,
  AnalyticsSummary,
  Payment,
  PaymentTransaction,
  Role,
  StudentProfile,
  Task,
  TeamMember,
} from './types';

// ─── Demo Persona Map ─────────────────────────────────────────────────────────
// Maps each role to the user who "plays" that role in the demo.
// RoleContext uses this to set current user identity when the role is switched.

export const DEMO_USER_ID: Record<Role, string> = {
  super_admin:     'tm-001', // Rajesh Kumar
  admin:           'tm-002', // Priya Sharma
  team_lead:       'tm-003', // Amit Verma
  marketing:       'tm-009', // Neha Sharma
  sales_executive: 'tm-004', // Rohan Gupta
  support_agent:   'tm-007', // Deepika Reddy
  student:         'sp-001', // Tanvi Saxena (StudentProfile, not TeamMember)
};

// ─── Team Members ─────────────────────────────────────────────────────────────

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'tm-001',
    name: 'Rajesh Kumar',
    email: 'rajesh.kumar@helpingbots.in',
    mobile: '+91-9876543200',
    role: 'super_admin',
    status: 'active',
    department: 'Founders',
    joinedAt: '2023-01-01T00:00:00Z',
    lastActiveAt: '2026-06-03T09:15:00Z',
  },
  {
    id: 'tm-002',
    name: 'Priya Sharma',
    email: 'priya.sharma@helpingbots.in',
    mobile: '+91-9876543201',
    role: 'admin',
    status: 'active',
    department: 'Operations',
    joinedAt: '2023-03-15T00:00:00Z',
    lastActiveAt: '2026-06-03T08:45:00Z',
  },
  {
    id: 'tm-003',
    name: 'Amit Verma',
    email: 'amit.verma@helpingbots.in',
    mobile: '+91-9876543202',
    role: 'team_lead',
    status: 'active',
    department: 'Admissions',
    joinedAt: '2023-06-01T00:00:00Z',
    lastActiveAt: '2026-06-03T09:00:00Z',
  },
  {
    id: 'tm-004',
    name: 'Rohan Gupta',
    email: 'rohan.gupta@helpingbots.in',
    mobile: '+91-9876543203',
    role: 'sales_executive',
    status: 'active',
    department: 'Admissions',
    joinedAt: '2024-01-10T00:00:00Z',
    lastActiveAt: '2026-06-03T09:30:00Z',
  },
  {
    id: 'tm-005',
    name: 'Kavya Nair',
    email: 'kavya.nair@helpingbots.in',
    mobile: '+91-9876543204',
    role: 'sales_executive',
    status: 'active',
    department: 'Admissions',
    joinedAt: '2024-02-14T00:00:00Z',
    lastActiveAt: '2026-06-03T09:10:00Z',
  },
  {
    id: 'tm-006',
    name: 'Arjun Singh',
    email: 'arjun.singh@helpingbots.in',
    mobile: '+91-9876543205',
    role: 'sales_executive',
    status: 'active',
    department: 'Admissions',
    joinedAt: '2024-03-01T00:00:00Z',
    lastActiveAt: '2026-06-02T18:20:00Z',
  },
  {
    id: 'tm-007',
    name: 'Deepika Reddy',
    email: 'deepika.reddy@helpingbots.in',
    mobile: '+91-9876543206',
    role: 'support_agent',
    status: 'active',
    department: 'Student Success',
    joinedAt: '2024-04-01T00:00:00Z',
    lastActiveAt: '2026-06-03T08:55:00Z',
  },
  {
    id: 'tm-008',
    name: 'Mohammed Ali',
    email: 'mohammed.ali@helpingbots.in',
    mobile: '+91-9876543207',
    role: 'support_agent',
    status: 'active',
    department: 'Student Success',
    joinedAt: '2024-05-15T00:00:00Z',
    lastActiveAt: '2026-06-03T09:05:00Z',
  },

  // In TEAM_MEMBERS array, add:
  {
    id: 'tm-009',
    name: 'Neha Sharma',
    email: 'neha.sharma@helpingbots.in',
    mobile: '+91-9876543207',
    role: 'marketing',
    status: 'active',
    department: 'Student Success',
    joinedAt: '2024-05-15T00:00:00Z',
    lastActiveAt: '2026-06-03T09:05:00Z',
  },

];

// ─── Leads ────────────────────────────────────────────────────────────────────
// 25 leads spread across all 10 lifecycle states.
// nextFollowUp values: some past (overdue), some today (Jun 3), some future.

export const LEADS: Lead[] = [
  // ── new (5) ──────────────────────────────────────────────────────────────
  {
    id: 'lead-001',
    name: 'Aarav Mehta',
    mobile: '+91-9812345678',
    email: 'aarav.mehta@gmail.com',
    program: 'MBA',
    degree: 'Postgraduate',
    college: 'Amity University, Noida',
    source: 'website',
    status: 'new',
    priority: 'high',
    assignedTo: 'tm-004',
    assignedToName: 'Rohan Gupta',
    generatedBy:     'tm-008',
    generatedByName: 'Harsh Sharma',
    nextFollowUp: '2026-06-04T10:00:00Z',
    createdAt: '2026-06-02T14:30:00Z',
    updatedAt: '2026-06-02T14:30:00Z',
  },
  {
    id: 'lead-002',
    name: 'Priya Krishnamurthy',
    mobile: '+91-9823456789',
    email: 'priya.k@gmail.com',
    program: 'B.Tech (Computer Science)',
    degree: 'Undergraduate',
    college: 'VIT University, Vellore',
    source: 'google_ads',
    status: 'new',
    priority: 'medium',
    assignedTo: 'tm-005',
    assignedToName: 'Kavya Nair',
    generatedBy:     'tm-009',
    generatedByName: 'Neha Sharma',
    nextFollowUp: '2026-06-05T11:00:00Z',
    createdAt: '2026-06-02T10:15:00Z',
    updatedAt: '2026-06-02T10:15:00Z',
  },
  {
    id: 'lead-003',
    name: 'Vikram Malhotra',
    mobile: '+91-9834567890',
    email: 'vikram.m@yahoo.com',
    program: 'BBA',
    degree: 'Undergraduate',
    college: 'Symbiosis Institute, Pune',
    source: 'referral',
    status: 'new',
    priority: 'low',
    assignedTo: 'tm-006',
    assignedToName: 'Arjun Singh',
    generatedBy:     'tm-011',
    generatedByName: 'Aman',
    nextFollowUp: '2026-06-06T10:00:00Z',
    createdAt: '2026-06-01T16:00:00Z',
    updatedAt: '2026-06-01T16:00:00Z',
  },
  {
    id: 'lead-004',
    name: 'Sneha Banerjee',
    mobile: '+91-9845678901',
    email: 'sneha.b@gmail.com',
    program: 'MCA',
    degree: 'Postgraduate',
    college: 'Manipal University, Jaipur',
    source: 'social_media',
    status: 'new',
    priority: 'high',
    assignedTo: 'tm-004',
    assignedToName: 'Rohan Gupta',
    generatedBy:     'tm-009',
    generatedByName: 'Neha Sharma',
    nextFollowUp: '2026-06-04T14:00:00Z',
    createdAt: '2026-06-01T09:30:00Z',
    updatedAt: '2026-06-01T09:30:00Z',
  },
  {
    id: 'lead-005',
    name: 'Karthik Subramanian',
    mobile: '+91-9856789012',
    email: 'karthik.s@gmail.com',
    program: 'B.Sc IT',
    degree: 'Undergraduate',
    college: 'SRM University, Chennai',
    source: 'whatsapp',
    status: 'new',
    priority: 'medium',
    assignedTo: 'tm-005',
    assignedToName: 'Kavya Nair',
    nextFollowUp: '2026-06-07T10:00:00Z',
    createdAt: '2026-06-01T11:45:00Z',
    updatedAt: '2026-06-01T11:45:00Z',
  },
  // ── contacted (3) ────────────────────────────────────────────────────────
  {
    id: 'lead-006',
    name: 'Aisha Khan',
    mobile: '+91-9867890123',
    email: 'aisha.k@gmail.com',
    program: 'B.Tech (Data Science)',
    degree: 'Undergraduate',
    college: 'Lovely Professional University, Punjab',
    source: 'email_campaign',
    status: 'contacted',
    priority: 'high',
    assignedTo: 'tm-004',
    assignedToName: 'Rohan Gupta',
    nextFollowUp: '2026-06-05T10:00:00Z',
    createdAt: '2026-05-28T09:00:00Z',
    updatedAt: '2026-05-29T11:30:00Z',
  },
  {
    id: 'lead-007',
    name: 'Rahul Joshi',
    mobile: '+91-9878901234',
    email: 'rahul.j@gmail.com',
    program: 'PGDM',
    degree: 'Postgraduate',
    college: 'Christ University, Bangalore',
    source: 'walk_in',
    status: 'contacted',
    priority: 'medium',
    assignedTo: 'tm-005',
    assignedToName: 'Kavya Nair',
    nextFollowUp: '2026-06-05T14:00:00Z',
    createdAt: '2026-05-27T13:00:00Z',
    updatedAt: '2026-05-28T10:00:00Z',
  },
  {
    id: 'lead-008',
    name: 'Divya Menon',
    mobile: '+91-9889012345',
    email: 'divya.m@gmail.com',
    program: 'MBA',
    degree: 'Postgraduate',
    college: 'Amity University, Noida',
    source: 'referral',
    status: 'contacted',
    priority: 'low',
    assignedTo: 'tm-006',
    assignedToName: 'Arjun Singh',
    nextFollowUp: '2026-06-06T10:00:00Z',
    createdAt: '2026-05-26T15:00:00Z',
    updatedAt: '2026-05-27T09:30:00Z',
  },
  // ── interested (3) ───────────────────────────────────────────────────────
  {
    id: 'lead-009',
    name: 'Ananya Sharma',
    mobile: '+91-9890123456',
    email: 'ananya.s@gmail.com',
    program: 'M.Tech (Artificial Intelligence)',
    degree: 'Postgraduate',
    college: 'UPES Dehradun',
    source: 'website',
    status: 'interested',
    priority: 'high',
    assignedTo: 'tm-005',
    assignedToName: 'Kavya Nair',
    nextFollowUp: '2026-06-04T10:00:00Z',
    createdAt: '2026-05-20T09:00:00Z',
    updatedAt: '2026-05-25T14:00:00Z',
  },
  {
    id: 'lead-010',
    name: 'Pooja Agarwal',
    mobile: '+91-9801234567',
    email: 'pooja.a@gmail.com',
    program: 'BBA',
    degree: 'Undergraduate',
    college: 'Symbiosis Institute, Pune',
    source: 'referral',
    status: 'interested',
    priority: 'high',
    assignedTo: 'tm-004',
    assignedToName: 'Rohan Gupta',
    nextFollowUp: '2026-06-03T11:00:00Z', // today
    createdAt: '2026-05-18T11:00:00Z',
    updatedAt: '2026-05-23T16:00:00Z',
  },
  {
    id: 'lead-011',
    name: 'Ravi Teja',
    mobile: '+91-9712345678',
    email: 'ravi.t@gmail.com',
    program: 'B.Tech (Computer Science)',
    degree: 'Undergraduate',
    college: 'VIT University, Vellore',
    source: 'google_ads',
    status: 'interested',
    priority: 'medium',
    assignedTo: 'tm-006',
    assignedToName: 'Arjun Singh',
    generatedBy:     'tm-009',
    generatedByName: 'Neha Sharma',
    nextFollowUp: '2026-06-05T10:00:00Z',
    createdAt: '2026-05-19T14:00:00Z',
    updatedAt: '2026-05-24T09:00:00Z',
  },
  // ── follow_up (3) — 2 overdue ────────────────────────────────────────────
  {
    id: 'lead-012',
    name: 'Meera Iyer',
    mobile: '+91-9723456789',
    email: 'meera.i@gmail.com',
    program: 'MCA',
    degree: 'Postgraduate',
    college: 'Chitkara University, Chandigarh',
    source: 'whatsapp',
    status: 'follow_up',
    priority: 'high',
    assignedTo: 'tm-006',
    assignedToName: 'Arjun Singh',
    nextFollowUp: '2026-06-03T10:00:00Z', // today
    createdAt: '2026-05-15T10:00:00Z',
    updatedAt: '2026-05-28T11:00:00Z',
  },
  {
    id: 'lead-013',
    name: 'Abhishek Tiwari',
    mobile: '+91-9734567890',
    email: 'abhi.t@gmail.com',
    program: 'MBA',
    degree: 'Postgraduate',
    college: 'Amity University, Noida',
    source: 'event',
    status: 'follow_up',
    priority: 'high',
    assignedTo: 'tm-004',
    assignedToName: 'Rohan Gupta',
    nextFollowUp: '2026-06-01T10:00:00Z', // overdue
    createdAt: '2026-05-14T13:00:00Z',
    updatedAt: '2026-05-26T10:00:00Z',
  },
  {
    id: 'lead-014',
    name: 'Naina Kapoor',
    mobile: '+91-9745678901',
    email: 'naina.k@gmail.com',
    program: 'B.Tech (Data Science)',
    degree: 'Undergraduate',
    college: 'Lovely Professional University, Punjab',
    source: 'website',
    status: 'follow_up',
    priority: 'medium',
    assignedTo: 'tm-005',
    assignedToName: 'Kavya Nair',
    generatedBy:     'tm-009',
    generatedByName: 'Neha Sharma',
    nextFollowUp: '2026-05-30T10:00:00Z', // overdue
    createdAt: '2026-05-12T09:00:00Z',
    updatedAt: '2026-05-22T14:00:00Z',
  },
  // ── application_started (1) ──────────────────────────────────────────────
  {
    id: 'lead-015',
    name: 'Ishaan Chatterjee',
    mobile: '+91-9756789012',
    email: 'ishaan.c@gmail.com',
    program: 'MBA',
    degree: 'Postgraduate',
    college: 'Amity University, Noida',
    source: 'referral',
    status: 'application_started',
    priority: 'high',
    assignedTo: 'tm-004',
    assignedToName: 'Rohan Gupta',
    nextFollowUp: '2026-06-06T10:00:00Z',
    createdAt: '2026-05-05T10:00:00Z',
    updatedAt: '2026-05-29T15:00:00Z',
  },
  // ── application_submitted (2) ────────────────────────────────────────────
  {
    id: 'lead-016',
    name: 'Gaurav Nanda',
    mobile: '+91-9767890123',
    email: 'gaurav.n@gmail.com',
    program: 'M.Tech (Artificial Intelligence)',
    degree: 'Postgraduate',
    college: 'UPES Dehradun',
    source: 'website',
    status: 'application_submitted',
    priority: 'high',
    assignedTo: 'tm-006',
    assignedToName: 'Arjun Singh',
    nextFollowUp: '2026-06-07T10:00:00Z',
    createdAt: '2026-04-28T09:00:00Z',
    updatedAt: '2026-05-30T13:00:00Z',
  },
  {
    id: 'lead-017',
    name: 'Ritika Singh',
    mobile: '+91-9778901234',
    email: 'ritika.s@gmail.com',
    program: 'BCA',
    degree: 'Undergraduate',
    college: 'Sharda University, Greater Noida',
    source: 'social_media',
    status: 'application_submitted',
    priority: 'high',
    assignedTo: 'tm-004',
    assignedToName: 'Rohan Gupta',
    generatedBy:     'tm-009',
    generatedByName: 'Neha Sharma',
    nextFollowUp: '2026-06-04T14:00:00Z',
    createdAt: '2026-04-25T11:00:00Z',
    updatedAt: '2026-05-28T16:00:00Z',
  },
  // ── admission_confirmed (1) ──────────────────────────────────────────────
  {
    id: 'lead-018',
    name: 'Yash Kulkarni',
    mobile: '+91-9789012345',
    email: 'yash.k@gmail.com',
    program: 'MBA',
    degree: 'Postgraduate',
    college: 'Symbiosis Institute, Pune',
    source: 'walk_in',
    status: 'admission_confirmed',
    priority: 'high',
    assignedTo: 'tm-005',
    assignedToName: 'Kavya Nair',
    nextFollowUp: '2026-06-05T11:00:00Z',
    createdAt: '2026-04-20T14:00:00Z',
    updatedAt: '2026-06-01T10:00:00Z',
  },
  // ── enrolled (4) ─────────────────────────────────────────────────────────
  {
    id: 'lead-019',
    name: 'Priyanka Rao',
    mobile: '+91-9790123456',
    email: 'priyanka.r@gmail.com',
    program: 'MBA',
    degree: 'Postgraduate',
    college: 'Amity University, Noida',
    source: 'referral',
    status: 'enrolled',
    priority: 'medium',
    assignedTo: 'tm-007',
    assignedToName: 'Deepika Reddy',
    nextFollowUp: null,
    createdAt: '2026-04-10T09:00:00Z',
    updatedAt: '2026-05-15T14:00:00Z',
  },
  {
    id: 'lead-020',
    name: 'Sameer Qureshi',
    mobile: '+91-9801234560',
    email: 'sameer.q@gmail.com',
    program: 'PGDM',
    degree: 'Postgraduate',
    college: 'Christ University, Bangalore',
    source: 'website',
    status: 'enrolled',
    priority: 'medium',
    assignedTo: 'tm-007',
    assignedToName: 'Deepika Reddy',
    nextFollowUp: null,
    createdAt: '2026-04-08T11:00:00Z',
    updatedAt: '2026-05-12T10:00:00Z',
  },
  {
    id: 'lead-021',
    name: 'Tanvi Saxena',
    mobile: '+91-9812345670',
    email: 'tanvi.s@gmail.com',
    program: 'B.Tech (Computer Science)',
    degree: 'Undergraduate',
    college: 'VIT University, Vellore',
    source: 'google_ads',
    status: 'enrolled',
    priority: 'medium',
    assignedTo: 'tm-008',
    assignedToName: 'Mohammed Ali',
    nextFollowUp: null,
    createdAt: '2026-04-05T10:00:00Z',
    updatedAt: '2026-05-10T15:00:00Z',
  },
  {
    id: 'lead-022',
    name: 'Rohan Mathur',
    mobile: '+91-9823456780',
    email: 'rohan.m@gmail.com',
    program: 'B.Tech (Data Science)',
    degree: 'Undergraduate',
    college: 'Lovely Professional University, Punjab',
    source: 'referral',
    status: 'enrolled',
    priority: 'low',
    assignedTo: 'tm-008',
    assignedToName: 'Mohammed Ali',
    nextFollowUp: null,
    createdAt: '2026-03-20T09:00:00Z',
    updatedAt: '2026-04-25T11:00:00Z',
  },
  // ── lost (2) ─────────────────────────────────────────────────────────────
  {
    id: 'lead-023',
    name: 'Harsh Vardhan',
    mobile: '+91-9834567800',
    email: 'harsh.v@gmail.com',
    program: 'BBA',
    degree: 'Undergraduate',
    college: 'Symbiosis Institute, Pune',
    source: 'google_ads',
    status: 'lost',
    priority: 'low',
    assignedTo: 'tm-006',
    assignedToName: 'Arjun Singh',
    generatedBy:     'tm-009',
    generatedByName: 'Neha Sharma',
    lostReason: 'Opted for a competitor institution',
    nextFollowUp: null,
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-05-20T14:00:00Z',
  },
  {
    id: 'lead-024',
    name: 'Pallavi Sethi',
    mobile: '+91-9845678900',
    email: 'pallavi.s@gmail.com',
    program: 'M.Tech (Artificial Intelligence)',
    degree: 'Postgraduate',
    college: 'UPES Dehradun',
    source: 'event',
    status: 'lost',
    priority: 'medium',
    assignedTo: 'tm-005',
    assignedToName: 'Kavya Nair',
    generatedBy:     'tm-009',
    generatedByName: 'Neha Sharma',
    lostReason: 'Budget constraints — may reconsider next year',
    nextFollowUp: null,
    createdAt: '2026-05-03T11:00:00Z',
    updatedAt: '2026-05-22T09:00:00Z',
  },
  // ── on_hold (1) ──────────────────────────────────────────────────────────
  {
    id: 'lead-025',
    name: 'Ajay Chauhan',
    mobile: '+91-9856789000',
    email: 'ajay.c@gmail.com',
    program: 'MBA',
    degree: 'Postgraduate',
    college: 'Amity University, Noida',
    source: 'phone',
    status: 'on_hold',
    priority: 'medium',
    assignedTo: 'tm-004',
    assignedToName: 'Rohan Gupta',
    notes: 'Needs to clear entrance exam first. Revisit in July.',
    nextFollowUp: '2026-07-01T10:00:00Z',
    createdAt: '2026-05-20T14:00:00Z',
    updatedAt: '2026-05-25T10:00:00Z',
  },
];

// ─── Lead Activities ──────────────────────────────────────────────────────────
// Timeline events for the lead detail drawer.
// Provided for two representative leads: one overdue follow-up, one full journey.

export const LEAD_ACTIVITIES: LeadActivity[] = [
  // ── lead-013 (Abhishek Tiwari — overdue follow_up) ────────────────────────
  {
    id: 'act-001',
    leadId: 'lead-013',
    type: 'status_change',
    title: 'Lead created',
    description: 'Added via HelpingBots event registration form.',
    performedBy: 'tm-001',
    performedByName: 'Rajesh Kumar',
    timestamp: '2026-05-14T13:00:00Z',
  },
  {
    id: 'act-002',
    leadId: 'lead-013',
    type: 'assignment_change',
    title: 'Assigned to Rohan Gupta',
    performedBy: 'tm-003',
    performedByName: 'Amit Verma',
    timestamp: '2026-05-14T13:05:00Z',
  },
  {
    id: 'act-003',
    leadId: 'lead-013',
    type: 'call_made',
    title: 'Introductory call completed',
    description: 'Student expressed interest in MBA. Requested fee brochure.',
    performedBy: 'tm-004',
    performedByName: 'Rohan Gupta',
    timestamp: '2026-05-15T11:00:00Z',
  },
  {
    id: 'act-004',
    leadId: 'lead-013',
    type: 'status_change',
    title: 'Status: new → contacted',
    performedBy: 'tm-004',
    performedByName: 'Rohan Gupta',
    timestamp: '2026-05-15T11:05:00Z',
  },
  {
    id: 'act-005',
    leadId: 'lead-013',
    type: 'email_sent',
    title: 'MBA brochure + fee structure sent via email',
    performedBy: 'tm-004',
    performedByName: 'Rohan Gupta',
    timestamp: '2026-05-16T10:30:00Z',
  },
  {
    id: 'act-006',
    leadId: 'lead-013',
    type: 'status_change',
    title: 'Status: contacted → interested',
    description: 'Student confirmed interest after reviewing the brochure.',
    performedBy: 'tm-004',
    performedByName: 'Rohan Gupta',
    timestamp: '2026-05-19T14:00:00Z',
  },
  {
    id: 'act-007',
    leadId: 'lead-013',
    type: 'status_change',
    title: 'Status: interested → follow_up',
    description: 'Needs family discussion before confirming.',
    performedBy: 'tm-004',
    performedByName: 'Rohan Gupta',
    timestamp: '2026-05-26T10:00:00Z',
  },
  {
    id: 'act-008',
    leadId: 'lead-013',
    type: 'note_added',
    title: 'Note added',
    description: 'Follow-up scheduled for June 1. Decision expected post-family discussion.',
    performedBy: 'tm-004',
    performedByName: 'Rohan Gupta',
    timestamp: '2026-05-26T10:05:00Z',
  },
  // ── lead-019 (Priyanka Rao — full enrolled journey) ───────────────────────
  {
    id: 'act-009',
    leadId: 'lead-019',
    type: 'status_change',
    title: 'Lead created',
    description: 'Referral from Sunita Mehta, current MBA student.',
    performedBy: 'tm-002',
    performedByName: 'Priya Sharma',
    timestamp: '2026-04-10T09:00:00Z',
  },
  {
    id: 'act-010',
    leadId: 'lead-019',
    type: 'call_made',
    title: 'First contact call — program overview shared',
    performedBy: 'tm-005',
    performedByName: 'Kavya Nair',
    timestamp: '2026-04-11T10:00:00Z',
  },
  {
    id: 'act-011',
    leadId: 'lead-019',
    type: 'status_change',
    title: 'Status: new → interested',
    description: 'Strong interest confirmed. Wants campus visit details.',
    performedBy: 'tm-005',
    performedByName: 'Kavya Nair',
    timestamp: '2026-04-15T14:00:00Z',
  },
  {
    id: 'act-012',
    leadId: 'lead-019',
    type: 'status_change',
    title: 'Status: interested → application_started',
    performedBy: 'tm-005',
    performedByName: 'Kavya Nair',
    timestamp: '2026-04-22T11:00:00Z',
  },
  {
    id: 'act-013',
    leadId: 'lead-019',
    type: 'document_uploaded',
    title: 'Documents submitted: Marksheets, ID proof, photographs',
    performedBy: 'tm-005',
    performedByName: 'Kavya Nair',
    timestamp: '2026-04-28T15:00:00Z',
  },
  {
    id: 'act-014',
    leadId: 'lead-019',
    type: 'status_change',
    title: 'Status: application_submitted → admission_confirmed',
    description: 'Offer letter issued by Amity University.',
    performedBy: 'tm-002',
    performedByName: 'Priya Sharma',
    timestamp: '2026-05-05T11:00:00Z',
  },
  {
    id: 'act-015',
    leadId: 'lead-019',
    type: 'payment_update',
    title: 'Full fee payment received — ₹4,20,000',
    performedBy: 'tm-007',
    performedByName: 'Deepika Reddy',
    timestamp: '2026-05-12T14:00:00Z',
  },
  {
    id: 'act-016',
    leadId: 'lead-019',
    type: 'status_change',
    title: 'Status: admission_confirmed → enrolled',
    performedBy: 'tm-007',
    performedByName: 'Deepika Reddy',
    timestamp: '2026-05-15T10:00:00Z',
  },
];

// ─── Tasks ────────────────────────────────────────────────────────────────────

export const TASKS: Task[] = [
  {
    id: 'task-001',
    leadId: 'lead-013',
    leadName: 'Abhishek Tiwari',
    title: 'Follow-up call — MBA decision pending',
    description: 'Was waiting for family discussion. Overdue since June 1.',
    type: 'call',
    status: 'overdue',
    priority: 'urgent',
    assignedTo: 'tm-004',
    assignedToName: 'Rohan Gupta',
    dueDate: '2026-06-01T10:00:00Z',
    createdAt: '2026-05-26T10:05:00Z',
    updatedAt: '2026-06-03T00:00:00Z',
  },
  {
    id: 'task-002',
    leadId: 'lead-014',
    leadName: 'Naina Kapoor',
    title: 'Send revised fee structure — B.Tech Data Science',
    description: 'Student requested scholarship breakdown. Overdue since May 30.',
    type: 'email',
    status: 'overdue',
    priority: 'high',
    assignedTo: 'tm-005',
    assignedToName: 'Kavya Nair',
    dueDate: '2026-05-30T10:00:00Z',
    createdAt: '2026-05-22T14:00:00Z',
    updatedAt: '2026-06-03T00:00:00Z',
  },
  {
    id: 'task-003',
    leadId: 'lead-010',
    leadName: 'Pooja Agarwal',
    title: 'Scheduled call — BBA program clarification',
    description: 'Student confirmed 11am call today to discuss placement stats.',
    type: 'call',
    status: 'pending',
    priority: 'high',
    assignedTo: 'tm-004',
    assignedToName: 'Rohan Gupta',
    dueDate: '2026-06-03T11:00:00Z',
    createdAt: '2026-05-30T15:00:00Z',
    updatedAt: '2026-05-30T15:00:00Z',
  },
  {
    id: 'task-004',
    leadId: 'lead-012',
    leadName: 'Meera Iyer',
    title: 'WhatsApp follow-up — MCA application status',
    type: 'whatsapp',
    status: 'pending',
    priority: 'high',
    assignedTo: 'tm-006',
    assignedToName: 'Arjun Singh',
    dueDate: '2026-06-03T12:00:00Z',
    createdAt: '2026-05-28T11:00:00Z',
    updatedAt: '2026-05-28T11:00:00Z',
  },
  {
    id: 'task-005',
    leadId: 'lead-018',
    leadName: 'Yash Kulkarni',
    title: 'Share fee payment link — MBA admission confirmed',
    description: 'Admission confirmed. Send payment link and June 20 deadline.',
    type: 'whatsapp',
    status: 'pending',
    priority: 'urgent',
    assignedTo: 'tm-005',
    assignedToName: 'Kavya Nair',
    dueDate: '2026-06-05T10:00:00Z',
    createdAt: '2026-06-01T10:00:00Z',
    updatedAt: '2026-06-01T10:00:00Z',
  },
  {
    id: 'task-006',
    leadId: 'lead-020',
    leadName: 'Sameer Qureshi',
    title: 'Second installment reminder — PGDM',
    description: 'Installment 2 of ₹2,35,000 due June 15.',
    type: 'call',
    status: 'pending',
    priority: 'high',
    assignedTo: 'tm-007',
    assignedToName: 'Deepika Reddy',
    dueDate: '2026-06-08T10:00:00Z',
    createdAt: '2026-06-01T09:00:00Z',
    updatedAt: '2026-06-01T09:00:00Z',
  },
  {
    id: 'task-007',
    leadId: 'lead-021',
    leadName: 'Tanvi Saxena',
    title: 'Collect pending documents — B.Tech CS',
    description: '10th Marksheet and Transfer Certificate still outstanding.',
    type: 'document',
    status: 'pending',
    priority: 'high',
    assignedTo: 'tm-008',
    assignedToName: 'Mohammed Ali',
    dueDate: '2026-06-10T10:00:00Z',
    createdAt: '2026-06-01T11:00:00Z',
    updatedAt: '2026-06-01T11:00:00Z',
  },
  {
    id: 'task-008',
    leadId: 'lead-015',
    leadName: 'Ishaan Chatterjee',
    title: 'Schedule campus visit — MBA application',
    description: 'Student wants a walkthrough before final submission.',
    type: 'meeting',
    status: 'pending',
    priority: 'medium',
    assignedTo: 'tm-004',
    assignedToName: 'Rohan Gupta',
    dueDate: '2026-06-06T10:00:00Z',
    createdAt: '2026-05-29T15:00:00Z',
    updatedAt: '2026-05-29T15:00:00Z',
  },
  {
    id: 'task-009',
    leadId: 'lead-009',
    leadName: 'Ananya Sharma',
    title: 'Email M.Tech AI placement report + faculty profiles',
    type: 'email',
    status: 'pending',
    priority: 'high',
    assignedTo: 'tm-005',
    assignedToName: 'Kavya Nair',
    dueDate: '2026-06-04T10:00:00Z',
    createdAt: '2026-06-02T10:00:00Z',
    updatedAt: '2026-06-02T10:00:00Z',
  },
  {
    id: 'task-010',
    leadId: 'lead-016',
    leadName: 'Gaurav Nanda',
    title: 'Application status update call',
    description: 'University is processing. Update student on expected timeline.',
    type: 'call',
    status: 'pending',
    priority: 'medium',
    assignedTo: 'tm-006',
    assignedToName: 'Arjun Singh',
    dueDate: '2026-06-07T11:00:00Z',
    createdAt: '2026-05-30T13:00:00Z',
    updatedAt: '2026-05-30T13:00:00Z',
  },
  {
    id: 'task-011',
    leadId: 'lead-019',
    leadName: 'Priyanka Rao',
    title: 'Orientation schedule and hostel details sent',
    type: 'email',
    status: 'completed',
    priority: 'medium',
    assignedTo: 'tm-007',
    assignedToName: 'Deepika Reddy',
    dueDate: '2026-05-20T10:00:00Z',
    completedAt: '2026-05-19T16:00:00Z',
    createdAt: '2026-05-16T09:00:00Z',
    updatedAt: '2026-05-19T16:00:00Z',
  },
  {
    id: 'task-012',
    leadId: 'lead-022',
    leadName: 'Rohan Mathur',
    title: 'Enrollment documentation verified and filed',
    type: 'document',
    status: 'completed',
    priority: 'high',
    assignedTo: 'tm-008',
    assignedToName: 'Mohammed Ali',
    dueDate: '2026-04-28T10:00:00Z',
    completedAt: '2026-04-27T14:00:00Z',
    createdAt: '2026-04-22T09:00:00Z',
    updatedAt: '2026-04-27T14:00:00Z',
  },
];

// ─── Payments ─────────────────────────────────────────────────────────────────

export const PAYMENTS: Payment[] = [
  {
    id: 'pay-001',
    leadId: 'lead-019',
    leadName: 'Priyanka Rao',
    program: 'MBA',
    totalAmount: 420000,
    paidAmount: 420000,
    dueAmount: 0,
    status: 'paid',
    dueDate: '2026-05-15T00:00:00Z',
    lastPaymentDate: '2026-05-12T14:00:00Z',
    invoiceNumber: 'INV-2026-0041',
    assignedTo: 'tm-007',
    assignedToName: 'Deepika Reddy',
    createdAt: '2026-05-05T11:00:00Z',
    updatedAt: '2026-05-12T14:00:00Z',
  },
  {
    id: 'pay-002',
    leadId: 'lead-020',
    leadName: 'Sameer Qureshi',
    program: 'PGDM',
    totalAmount: 480000,
    paidAmount: 245000,
    dueAmount: 235000,
    status: 'partially_paid',
    dueDate: '2026-06-15T00:00:00Z',
    lastPaymentDate: '2026-05-10T11:00:00Z',
    invoiceNumber: 'INV-2026-0039',
    assignedTo: 'tm-007',
    assignedToName: 'Deepika Reddy',
    notes: 'Instalment 2 of ₹2,35,000 due June 15.',
    createdAt: '2026-04-15T10:00:00Z',
    updatedAt: '2026-05-10T11:00:00Z',
  },
  {
    id: 'pay-003',
    leadId: 'lead-021',
    leadName: 'Tanvi Saxena',
    program: 'B.Tech (Computer Science)',
    totalAmount: 320000,
    paidAmount: 160000,
    dueAmount: 160000,
    status: 'partially_paid',
    dueDate: '2026-06-30T00:00:00Z',
    lastPaymentDate: '2026-05-08T13:00:00Z',
    invoiceNumber: 'INV-2026-0037',
    assignedTo: 'tm-008',
    assignedToName: 'Mohammed Ali',
    notes: 'Balance ₹1,60,000 confirmed by student for June 30.',
    createdAt: '2026-04-12T09:00:00Z',
    updatedAt: '2026-05-08T13:00:00Z',
  },
  {
    id: 'pay-004',
    leadId: 'lead-022',
    leadName: 'Rohan Mathur',
    program: 'B.Tech (Data Science)',
    totalAmount: 280000,
    paidAmount: 280000,
    dueAmount: 0,
    status: 'paid',
    dueDate: '2026-04-30T00:00:00Z',
    lastPaymentDate: '2026-04-24T10:00:00Z',
    invoiceNumber: 'INV-2026-0028',
    assignedTo: 'tm-008',
    assignedToName: 'Mohammed Ali',
    createdAt: '2026-03-25T10:00:00Z',
    updatedAt: '2026-04-24T10:00:00Z',
  },
  {
    id: 'pay-005',
    leadId: 'lead-018',
    leadName: 'Yash Kulkarni',
    program: 'MBA',
    totalAmount: 420000,
    paidAmount: 0,
    dueAmount: 420000,
    status: 'pending',
    dueDate: '2026-06-20T00:00:00Z',
    invoiceNumber: 'INV-2026-0052',
    assignedTo: 'tm-005',
    assignedToName: 'Kavya Nair',
    notes: 'Admission confirmed June 1. Awaiting first payment.',
    createdAt: '2026-06-01T10:00:00Z',
    updatedAt: '2026-06-01T10:00:00Z',
  },
];

export const PAYMENT_TRANSACTIONS: PaymentTransaction[] = [
  {
    id: 'txn-001',
    paymentId: 'pay-001',
    amount: 420000,
    method: 'bank_transfer',
    reference: 'NEFT-20260512-001234',
    date: '2026-05-12T14:00:00Z',
    note: 'Full payment. Enrollment confirmed.',
  },
  {
    id: 'txn-002',
    paymentId: 'pay-002',
    amount: 150000,
    method: 'upi',
    reference: 'UPI-20260415-005678',
    date: '2026-04-15T11:00:00Z',
    note: 'Instalment 1 of 3',
  },
  {
    id: 'txn-003',
    paymentId: 'pay-002',
    amount: 95000,
    method: 'bank_transfer',
    reference: 'NEFT-20260510-009012',
    date: '2026-05-10T11:00:00Z',
    note: 'Instalment 2 of 3',
  },
  {
    id: 'txn-004',
    paymentId: 'pay-003',
    amount: 160000,
    method: 'upi',
    reference: 'UPI-20260508-003456',
    date: '2026-05-08T13:00:00Z',
    note: 'First instalment paid',
  },
  {
    id: 'txn-005',
    paymentId: 'pay-004',
    amount: 140000,
    method: 'bank_transfer',
    reference: 'NEFT-20260410-007890',
    date: '2026-04-10T10:00:00Z',
    note: 'Instalment 1 of 2',
  },
  {
    id: 'txn-006',
    paymentId: 'pay-004',
    amount: 140000,
    method: 'upi',
    reference: 'UPI-20260424-001234',
    date: '2026-04-24T10:00:00Z',
    note: 'Instalment 2 of 2 — course fully cleared',
  },
];

// ─── Import Jobs ──────────────────────────────────────────────────────────────

export const IMPORT_JOBS: ImportJob[] = [
  {
    id: 'imp-001',
    fileName: 'leads_may2026_final.csv',
    fileSize: 24576,
    totalRows: 48,
    validRows: 45,
    invalidRows: 2,
    duplicateRows: 1,
    status: 'imported',
    uploadedBy: 'tm-002',
    uploadedByName: 'Priya Sharma',
    approvedBy: 'tm-001',
    approvedByName: 'Rajesh Kumar',
    createdAt: '2026-06-01T09:00:00Z',
    updatedAt: '2026-06-01T11:30:00Z',
  },
  {
    id: 'imp-002',
    fileName: 'leads_june2026_batch1.csv',
    fileSize: 18432,
    totalRows: 32,
    validRows: 28,
    invalidRows: 2,
    duplicateRows: 2,
    status: 'pending_approval',
    uploadedBy: 'tm-003',
    uploadedByName: 'Amit Verma',
    createdAt: '2026-06-02T14:30:00Z',
    updatedAt: '2026-06-02T14:35:00Z',
  },
  {
    id: 'imp-003',
    fileName: 'walk_in_leads_may.xlsx',
    fileSize: 10240,
    totalRows: 15,
    validRows: 0,
    invalidRows: 15,
    duplicateRows: 0,
    status: 'validation_failed',
    uploadedBy: 'tm-003',
    uploadedByName: 'Amit Verma',
    rejectionReason:
      'Mobile number column is missing. Map columns and resubmit.',
    createdAt: '2026-05-28T16:00:00Z',
    updatedAt: '2026-05-28T16:05:00Z',
  },
  {
    id: 'imp-004',
    fileName: 'leads_april2026.csv',
    fileSize: 30720,
    totalRows: 60,
    validRows: 58,
    invalidRows: 1,
    duplicateRows: 1,
    status: 'imported',
    uploadedBy: 'tm-002',
    uploadedByName: 'Priya Sharma',
    approvedBy: 'tm-001',
    approvedByName: 'Rajesh Kumar',
    createdAt: '2026-05-02T10:00:00Z',
    updatedAt: '2026-05-02T12:15:00Z',
  },
];

// Sample rows for the pending_approval import (imp-002)
export const IMPORT_PREVIEW_ROWS: ImportRow[] = [
  {
    rowIndex: 1,
    rawData: {
      Name: 'Ankit Sharma', Mobile: '9988776655',
      Email: 'ankit.sharma@gmail.com', Program: 'MBA',
      Source: 'Google Ads', Priority: 'High',
      College: 'Amity University, Noida', Degree: 'Postgraduate',
      'Assigned To': 'Rohan Gupta',
    },
    mappedData: {
      name: 'Ankit Sharma', mobile: '+91-9988776655',
      email: 'ankit.sharma@gmail.com', program: 'MBA',
      source: 'google_ads', status: 'new', priority: 'high',
      college: 'Amity University, Noida', degree: 'Postgraduate',
      assignedToName: 'Rohan Gupta',
    },
    errors: [],
    warnings: [],
    isDuplicate: false,
    status: 'valid',
  },
  {
    rowIndex: 2,
    rawData: {
      Name: 'Sunita Yadav', Mobile: '8877665544',
      Email: 'sunita.y@gmail.com', Program: 'BCA',
      Source: 'Website', Priority: 'Medium',
      College: 'Sharda University', Degree: 'Undergraduate',
      'Assigned To': 'Kavya Nair',
    },
    mappedData: {
      name: 'Sunita Yadav', mobile: '+91-8877665544',
      email: 'sunita.y@gmail.com', program: 'BCA',
      source: 'website', status: 'new', priority: 'medium',
      college: 'Sharda University', degree: 'Undergraduate',
      assignedToName: 'Kavya Nair',
    },
    errors: [],
    warnings: [
      'College "Sharda University" — did you mean "Sharda University, Greater Noida"?',
    ],
    isDuplicate: false,
    status: 'warning',
  },
  {
    rowIndex: 3,
    rawData: {
      Name: 'Priya Krishnamurthy', Mobile: '9823456789',
      Email: 'priya.k@gmail.com', Program: 'B.Tech CS',
      Source: 'Google Ads', College: 'VIT University, Vellore',
      Degree: 'Undergraduate', 'Assigned To': 'Kavya Nair',
    },
    mappedData: {
      name: 'Priya Krishnamurthy', mobile: '+91-9823456789',
      email: 'priya.k@gmail.com',
    },
    errors: [],
    warnings: [],
    isDuplicate: true,
    status: 'duplicate',
  },
  {
    rowIndex: 4,
    rawData: {
      Name: 'Deepak Nair', Mobile: '',
      Email: 'deepak.nair@outlook.com', Program: 'PGDM',
      Source: 'Referral', Priority: 'High',
      College: 'Christ University', Degree: 'Postgraduate',
      'Assigned To': 'Arjun Singh',
    },
    mappedData: {
      name: 'Deepak Nair', email: 'deepak.nair@outlook.com',
      program: 'PGDM', source: 'referral',
    },
    errors: ['Mobile number is required and cannot be empty'],
    warnings: [],
    isDuplicate: false,
    status: 'invalid',
  },
  {
    rowIndex: 5,
    rawData: {
      Name: 'Shreya Kapoor', Mobile: '7766554433',
      Email: 'shreya.k@gmail.com', Program: 'M.Tech AI',
      Source: 'Social Media', Priority: 'High',
      College: 'UPES Dehradun', Degree: 'Postgraduate',
      'Assigned To': 'Rohan Gupta',
    },
    mappedData: {
      name: 'Shreya Kapoor', mobile: '+91-7766554433',
      email: 'shreya.k@gmail.com',
      program: 'M.Tech (Artificial Intelligence)',
      source: 'social_media', status: 'new', priority: 'high',
      college: 'UPES Dehradun', degree: 'Postgraduate',
      assignedToName: 'Rohan Gupta',
    },
    errors: [],
    warnings: [],
    isDuplicate: false,
    status: 'valid',
  },
];

// ─── Leaderboard ──────────────────────────────────────────────────────────────

export const LEADERBOARD: LeaderboardEntry[] = [
  {
    rank: 1,
    userId: 'tm-005',
    name: 'Kavya Nair',
    enrollments: 4,
    target: 5,
    targetAchieved: 80,
    revenue: 1760000,
    calls: 68,
    meetings: 12,
    delta: 1,
    period: 'month',
  },
  {
    rank: 2,
    userId: 'tm-004',
    name: 'Rohan Gupta',
    enrollments: 3,
    target: 5,
    targetAchieved: 60,
    revenue: 1350000,
    calls: 72,
    meetings: 9,
    delta: 0,
    period: 'month',
  },
  {
    rank: 3,
    userId: 'tm-006',
    name: 'Arjun Singh',
    enrollments: 2,
    target: 4,
    targetAchieved: 50,
    revenue: 840000,
    calls: 54,
    meetings: 7,
    delta: -1,
    period: 'month',
  },
  {
    rank: 4,
    userId: 'tm-extra-01',
    name: 'Sunita Kapoor',
    enrollments: 2,
    target: 4,
    targetAchieved: 50,
    revenue: 780000,
    calls: 49,
    meetings: 6,
    delta: 2,
    period: 'month',
  },
  {
    rank: 5,
    userId: 'tm-extra-02',
    name: 'Vikas Sharma',
    enrollments: 1,
    target: 4,
    targetAchieved: 25,
    revenue: 380000,
    calls: 41,
    meetings: 4,
    delta: -1,
    period: 'month',
  },
  {
    rank: 6,
    userId: 'tm-extra-03',
    name: 'Priya Jain',
    enrollments: 1,
    target: 3,
    targetAchieved: 33,
    revenue: 320000,
    calls: 38,
    meetings: 3,
    delta: -1,
    period: 'month',
  },

  {
    rank:            1,
    userId:          'tm-004',
    name:            'Rohan Gupta',
    enrollments:     2,
    target:          2,
    targetAchieved:  100,
    revenue:         840000,
    calls:           22,
    meetings:        4,
    delta:           2,
    period:          'week',
  },
  {
    rank:            2,
    userId:          'tm-005',
    name:            'Kavya Nair',
    enrollments:     1,
    target:          2,
    targetAchieved:  50,
    revenue:         420000,
    calls:           18,
    meetings:        3,
    delta:           -1,
    period:          'week',
  },
  {
    rank:            3,
    userId:          'tm-006',
    name:            'Arjun Singh',
    enrollments:     1,
    target:          2,
    targetAchieved:  50,
    revenue:         320000,
    calls:           15,
    meetings:        2,
    delta:           0,
    period:          'week',
  },
  {
    rank:            4,
    userId:          'tm-extra-01',
    name:            'Sunita Kapoor',
    enrollments:     0,
    target:          2,
    targetAchieved:  0,
    revenue:         0,
    calls:           12,
    meetings:        1,
    delta:           -1,
    period:          'week',
  },
  {
    rank:            5,
    userId:          'tm-extra-02',
    name:            'Vikas Sharma',
    enrollments:     0,
    target:          2,
    targetAchieved:  0,
    revenue:         0,
    calls:           9,
    meetings:        0,
    delta:           0,
    period:          'week',
  },
];

// ─── Analytics ────────────────────────────────────────────────────────────────

export const ANALYTICS: AnalyticsSummary = {
  period: 'June 2026',
  totalLeads: 25,
  newLeads: 8,
  converted: 4,
  lost: 2,
  conversionRate: 16.0,
  avgResponseTimeHours: 4.2,
  revenueCollected: 1480000,
  revenuePending: 815000,
  topSources: [
    { source: 'website', count: 6 },
    { source: 'google_ads', count: 5 },
    { source: 'referral', count: 5 },
    { source: 'social_media', count: 3 },
    { source: 'whatsapp', count: 2 },
    { source: 'walk_in', count: 2 },
    { source: 'event', count: 2 },
  ],
  topPrograms: [
    { program: 'MBA', count: 8 },
    { program: 'B.Tech (Computer Science)', count: 4 },
    { program: 'PGDM', count: 3 },
    { program: 'B.Tech (Data Science)', count: 3 },
    { program: 'M.Tech (Artificial Intelligence)', count: 3 },
  ],
  statusDistribution: [
    { status: 'new', count: 5 },
    { status: 'contacted', count: 3 },
    { status: 'interested', count: 3 },
    { status: 'follow_up', count: 3 },
    { status: 'application_started', count: 1 },
    { status: 'application_submitted', count: 2 },
    { status: 'admission_confirmed', count: 1 },
    { status: 'enrolled', count: 4 },
    { status: 'lost', count: 2 },
    { status: 'on_hold', count: 1 },
  ],
  trend: [
    { label: 'Apr W3', leads: 8,  enrolled: 2, lost: 1 },
    { label: 'Apr W4', leads: 6,  enrolled: 1, lost: 0 },
    { label: 'May W1', leads: 10, enrolled: 2, lost: 1 },
    { label: 'May W2', leads: 7,  enrolled: 1, lost: 1 },
    { label: 'May W3', leads: 9,  enrolled: 3, lost: 0 },
    { label: 'May W4', leads: 11, enrolled: 2, lost: 1 },
    { label: 'Jun W1', leads: 8,  enrolled: 1, lost: 0 },
  ],
};

// ─── Student Profile ──────────────────────────────────────────────────────────
// Tanvi Saxena — lead-021, enrolled, partially paid, 2 documents pending.

export const STUDENT_PROFILE: StudentProfile = {
  id: 'sp-001',
  leadId: 'lead-021',
  name: 'Tanvi Saxena',
  email: 'tanvi.s@gmail.com',
  mobile: '+91-9812345670',
  program: 'B.Tech (Computer Science)',
  college: 'VIT University, Vellore',
  degree: 'Undergraduate',
  applicationStage: 'fee_pending',
  counselorName: 'Mohammed Ali',
  counselorEmail: 'mohammed.ali@helpingbots.in',
  counselorMobile: '+91-9876543207',
  pendingDocuments: ['10th Marksheet', 'Transfer Certificate'],
  paymentStatus: 'partially_paid',
  totalFee: 320000,
  paidAmount: 160000,
  nextActionTitle: 'Complete Your Fee Payment',
  nextActionDescription:
    '₹1,60,000 remaining. Due by June 30, 2026. Contact your counselor for the payment link.',
  milestones: [
    {
      id: 'ms-001', order: 1,
      title: 'Application Received',
      description: 'Your application has been successfully received.',
      completedAt: '2026-04-05T10:00:00Z',
      isCompleted: true,
    },
    {
      id: 'ms-002', order: 2,
      title: 'Under Review',
      description: 'Our admissions team reviewed your application.',
      completedAt: '2026-04-12T11:00:00Z',
      isCompleted: true,
    },
    {
      id: 'ms-003', order: 3,
      title: 'Documents Submitted',
      description: 'Required documents uploaded and verified.',
      completedAt: '2026-04-20T14:00:00Z',
      isCompleted: true,
    },
    {
      id: 'ms-004', order: 4,
      title: 'Admission Confirmed',
      description: 'Congratulations! Your admission has been confirmed by VIT.',
      completedAt: '2026-04-28T16:00:00Z',
      isCompleted: true,
    },
    {
      id: 'ms-005', order: 5,
      title: 'Fee Payment',
      description: 'Complete fee payment to secure your seat.',
      isCompleted: false,
    },
    {
      id: 'ms-006', order: 6,
      title: 'Enrollment Complete',
      description: 'Enrollment confirmed after full fee clearance.',
      isCompleted: false,
    },
    {
      id: 'ms-007', order: 7,
      title: 'Orientation',
      description: 'Attend orientation and meet your batch.',
      isCompleted: false,
    },
  ],
  createdAt: '2026-04-05T10:00:00Z',
};

// ─── Dashboard Metrics ────────────────────────────────────────────────────────
// allowedRoles controls which metrics each role sees on their dashboard.
// trend: direction the number is moving. UI decides whether that's good/bad.

export const DASHBOARD_METRICS: DashboardMetric[] = [
  {
    id: 'metric-001',
    label: 'Total Active Leads',
    value: 19,
    change: 12,
    trend: 'up',
    format: 'number',
    allowedRoles: ['super_admin', 'admin', 'team_lead'],
  },
  {
    id: 'metric-002',
    label: 'New This Week',
    value: 5,
    change: 25,
    trend: 'up',
    format: 'number',
    allowedRoles: ['super_admin', 'admin', 'team_lead', 'sales_executive'],
  },
  {
    id: 'metric-003',
    label: 'Enrolled This Month',
    value: 4,
    change: 33,
    trend: 'up',
    format: 'number',
    allowedRoles: ['super_admin', 'admin', 'team_lead', 'sales_executive'],
  },
  {
    id: 'metric-004',
    label: 'Conversion Rate',
    value: 16,
    change: 2.1,
    trend: 'up',
    format: 'percentage',
    allowedRoles: ['super_admin', 'admin', 'team_lead'],
  },
  {
    id: 'metric-005',
    label: 'Revenue Collected',
    value: 1480000,
    change: 18,
    trend: 'up',
    format: 'currency',
    allowedRoles: ['super_admin', 'admin'],
  },
  {
    id: 'metric-006',
    label: 'Revenue Pending',
    value: 815000,
    change: -5,
    trend: 'down',
    format: 'currency',
    allowedRoles: ['super_admin', 'admin', 'support_agent'],
  },
  {
    id: 'metric-007',
    label: 'Tasks Overdue',
    value: 2,
    change: -33,
    trend: 'down',
    format: 'number',
    allowedRoles: ['super_admin', 'admin', 'team_lead', 'sales_executive', 'support_agent'],
  },
  {
    id: 'metric-008',
    label: 'Avg Response Time',
    value: 4.2,
    change: -16,
    trend: 'down',
    format: 'duration',
    allowedRoles: ['super_admin', 'admin'],
  },
  {
    id: 'metric-009',
    label: 'My Active Leads',
    value: 8,
    change: 14,
    trend: 'up',
    format: 'number',
    allowedRoles: ['sales_executive'],
  },
  {
    id: 'metric-010',
    label: 'My Tasks Today',
    value: 3,
    change: 0,
    trend: 'neutral',
    format: 'number',
    allowedRoles: ['sales_executive', 'support_agent'],
  },
  {
    id: 'metric-011',
    label: 'My Overdue Tasks',
    value: 1,
    change: 0,
    trend: 'neutral',
    format: 'number',
    allowedRoles: ['sales_executive', 'support_agent'],
  },
  {
    id: 'metric-012',
    label: 'Enrolled Students',
    value: 4,
    change: 33,
    trend: 'up',
    format: 'number',
    allowedRoles: ['support_agent'],
  },
  {
    id: 'metric-013',
    label: 'Fee Paid',
    value: 160000,
    change: 0,
    trend: 'neutral',
    format: 'currency',
    allowedRoles: ['student'],
  },
  {
    id: 'metric-014',
    label: 'Balance Due',
    value: 160000,
    change: 0,
    trend: 'neutral',
    format: 'currency',
    allowedRoles: ['student'],
  },
];

// ─── Audit Logs ───────────────────────────────────────────────────────────────

export const AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit-001',
    actorId: 'tm-003',
    actorName: 'Amit Verma',
    entityType: 'import',
    entityId: 'imp-002',
    action: 'import_uploaded',
    afterJson: { fileName: 'leads_june2026_batch1.csv', totalRows: 32 },
    source: 'ui',
    timestamp: '2026-06-02T14:30:00Z',
  },
  {
    id: 'audit-002',
    actorId: 'tm-004',
    actorName: 'Rohan Gupta',
    entityType: 'lead',
    entityId: 'lead-013',
    action: 'lead_status_changed',
    beforeJson: { status: 'interested' },
    afterJson: { status: 'follow_up' },
    source: 'ui',
    timestamp: '2026-05-26T10:00:00Z',
  },
  {
    id: 'audit-003',
    actorId: 'tm-007',
    actorName: 'Deepika Reddy',
    entityType: 'payment',
    entityId: 'pay-001',
    action: 'payment_updated',
    beforeJson: { status: 'pending', paidAmount: 0 },
    afterJson: { status: 'paid', paidAmount: 420000 },
    source: 'ui',
    timestamp: '2026-05-12T14:00:00Z',
  },
  {
    id: 'audit-004',
    actorId: 'tm-001',
    actorName: 'Rajesh Kumar',
    entityType: 'import',
    entityId: 'imp-001',
    action: 'import_approved',
    afterJson: { status: 'approved', approvedRows: 45 },
    source: 'ui',
    timestamp: '2026-06-01T11:00:00Z',
  },
  {
    id: 'audit-005',
    actorId: 'tm-002',
    actorName: 'Priya Sharma',
    entityType: 'user',
    entityId: 'tm-008',
    action: 'user_created',
    afterJson: { name: 'Mohammed Ali', role: 'support_agent' },
    source: 'ui',
    timestamp: '2024-05-15T10:00:00Z',
  },
];